#debug or release
RUN_MODE = "debug"

[casbin]
    ModelPath = './rbac_model.conf'
    
[app]
    Template = "view/**/*"
    PageSize = 10
    JwtSecret = "23347$040412"
    SigningMethod = "HS256" 
    JwtExpiresAt = "6h"
    PidPath = "./pid.lock"
[log]
    Level = "trace"
    ReportCaller = false
    Formatter = "json"

[server]
    HttpAddress="0.0.0.0"
    HttpPort = 8080
    ReadTimeout = 2
    WriteTimeout = 6

[mysql]
    LogMode = false
    MysqlUser = "root"
    Config = "charset=utf8mb4&parseTime=True&loc=Local"
    MysqlPassword = "123456"
    MysqlHost = "192.168.99.100:3306"
    MysqlName = "test"
    MysqlPrefix = "test_"
    MaxLifetime = 30