#debug or release
RUN_MODE = "debug"

[casbin]
    ModelPath = 'static/config/rbac_model.conf'
[cookie]
    Mode = "AES_CBC"
    key = "zx4d646d80884bfe"
    iv  = "M/a92281101737a6"
    padding = "PKCS7"
[session]
    maxAge = 86400
    ##Default Session Driver "cookie","redis"
    driver = "cookie"
    cookie = "SESSION"
    path = "/"
    domain = "localhost"
    secure = false
    http_only = true
    same_site = 1
[captcha]
    KeyLen = 4
    ImgWidth = 200
    imgHeight = 80
    MaxSkew = 0.7
    DotCount = 80
[app]
    Template = "view/**/*"
    PageSize = 10
    JwtSecret = "23347$040412"
    SigningMethod = "HS256" 
    JwtExpiresAt = "6h"
    PidPath = "./pid.lock"
[log]
    Level = "info"
    Formatter = "json"
    ShowLine = false
    OutFile = true
    LogInConsole = true
    LogDir = "log"
[server]
    HttpAddress="0.0.0.0"
    HttpPort = 8080
    ReadTimeout = 2
    WriteTimeout = 6
[mysql.global]
    LogMode = "Info"
    MaxLifetime = 30
    MaxIdleTime = 10
    MaxOpenConns = 10
    MaxIdleConns = 2
    slave = 2
[mysql.master]
    User = "root"
    Config = "charset=utf8mb4&parseTime=True&loc=Local"
    Password = "123456"
    Host = "192.168.99.100:3306"
    DBName = "test"
[mysql.slave.0]
    User = "root"
    Config = "charset=utf8mb4&parseTime=True&loc=Local"
    Password = "123456"
    Host = "192.168.99.100:3306"
    DBName = "test"
[mysql.slave.1]
    User = "root"
    Config = "charset=utf8mb4&parseTime=True&loc=Local"
    Password = "123456"
    Host = "192.168.99.100:3306"
    DBName = "test"